import { Request, Response } from 'express';
import { prisma } from '../config/prisma';
import { AuthRequest } from '../middlewares/auth';
import { deleteFileFromStorage } from '../utils/storage';
import { resend } from '../config/resend';

// ═══════════════════════════════════════════════════════════════════════════════
// CONTACT MESSAGE
// ═══════════════════════════════════════════════════════════════════════════════

export const submitContactMessage = async (req: Request, res: Response): Promise<void> => {
  try {
    const { name, email, subject, message } = req.body;
    if (!name || !email || !message) {
      res.status(400).json({ success: false, message: 'Name, email, and message are required.' });
      return;
    }
    const contactMessage = await prisma.contactMessage.create({
      data: { name, email, subject: subject || null, message },
    });

    // Send email alert via Resend SDK
    if (resend) {
      try {
        await resend.emails.send({
          from: 'Sapirox Web <onboarding@resend.dev>', // Resend standard sandbox sender
          to: 'info@sapirox.com',
          subject: `[Lead Notification] ${subject || 'New Contact Request'}`,
          html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
              <h2 style="color: #4f46e5; border-bottom: 2px solid #f3f4f6; padding-bottom: 10px;">New Contact Lead Received</h2>
              <p><strong>Name:</strong> ${name}</p>
              <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
              <p><strong>Subject:</strong> ${subject || 'N/A'}</p>
              <div style="background-color: #f9fafb; padding: 15px; border-left: 4px solid #4f46e5; border-radius: 4px; margin-top: 20px;">
                <p style="margin: 0; font-style: italic;">"${message}"</p>
              </div>
              <footer style="margin-top: 30px; font-size: 11px; color: #666; text-align: center; border-top: 1px solid #f3f4f6; padding-top: 15px;">
                This message was automatically generated by Sapirox CMS Portal.
              </footer>
            </div>
          `
        });
        console.log('✅ Email notification sent successfully via Resend');
      } catch (emailErr) {
        console.error('⚠️ Failed to send email via Resend:', emailErr);
      }
    }

    res.status(201).json({ success: true, data: contactMessage });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to send message.' });
  }
};

export const getAllMessages = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { status } = req.query;
    const where: Record<string, unknown> = {};
    if (status) where.status = status as string;

    const messages = await prisma.contactMessage.findMany({
      where,
      orderBy: { createdAt: 'desc' },
    });
    res.status(200).json({ success: true, data: messages });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch messages.' });
  }
};

export const updateMessageStatus = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    if (!status || !['UNREAD', 'REPLIED', 'ARCHIVED', 'DELETED'].includes(status)) {
      res.status(400).json({ success: false, message: 'Valid status required.' });
      return;
    }
    const message = await prisma.contactMessage.update({
      where: { id },
      data: { status },
    });
    res.status(200).json({ success: true, data: message });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to update message.' });
  }
};

export const deleteMessage = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    await prisma.contactMessage.delete({ where: { id: req.params.id } });
    res.status(200).json({ success: true, message: 'Message deleted.' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to delete message.' });
  }
};

// ═══════════════════════════════════════════════════════════════════════════════
// TESTIMONIALS
// ═══════════════════════════════════════════════════════════════════════════════

export const getPublicTestimonials = async (_req: Request, res: Response): Promise<void> => {
  try {
    const testimonials = await prisma.testimonial.findMany({ orderBy: { order: 'asc' } });
    res.status(200).json({ success: true, data: testimonials });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch testimonials.' });
  }
};

export const createTestimonial = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { name, role, avatar, feedback, order } = req.body;
    if (!name || !role || !feedback) {
      res.status(400).json({ success: false, message: 'Name, role, and feedback are required.' });
      return;
    }
    const testimonial = await prisma.testimonial.create({
      data: { name, role, avatar: avatar || null, feedback, order: order || 0 },
    });
    res.status(201).json({ success: true, data: testimonial });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to create testimonial.' });
  }
};

export const updateTestimonial = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const existing = await prisma.testimonial.findUnique({ where: { id } });
    if (!existing) {
      res.status(404).json({ success: false, message: 'Testimonial not found.' });
      return;
    }

    // Clean up replaced avatar asynchronously
    if (req.body.avatar !== undefined && existing.avatar && existing.avatar !== req.body.avatar) {
      deleteFileFromStorage(existing.avatar).catch(err => {
        console.error('Error during testimonial avatar update cleanup:', err);
      });
    }

    const testimonial = await prisma.testimonial.update({ where: { id }, data: req.body });
    res.status(200).json({ success: true, data: testimonial });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to update testimonial.' });
  }
};

export const deleteTestimonial = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const existing = await prisma.testimonial.findUnique({ where: { id } });
    if (!existing) {
      res.status(404).json({ success: false, message: 'Testimonial not found.' });
      return;
    }

    // Clean up avatar image from storage asynchronously
    if (existing.avatar) {
      deleteFileFromStorage(existing.avatar).catch(err => {
        console.error('Error during testimonial avatar cleanup:', err);
      });
    }

    await prisma.testimonial.delete({ where: { id } });
    res.status(200).json({ success: true, message: 'Testimonial deleted.' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to delete testimonial.' });
  }
};

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORIES & TAGS
// ═══════════════════════════════════════════════════════════════════════════════

export const getCategories = async (_req: Request, res: Response): Promise<void> => {
  try {
    const categories = await prisma.category.findMany();
    res.status(200).json({ success: true, data: categories });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch categories.' });
  }
};

export const createCategory = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { name, slug } = req.body;
    if (!name || !slug) {
      res.status(400).json({ success: false, message: 'Name and slug are required.' });
      return;
    }
    const category = await prisma.category.create({ data: { name, slug } });
    res.status(201).json({ success: true, data: category });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to create category.' });
  }
};

export const deleteCategory = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    await prisma.category.delete({ where: { id: req.params.id } });
    res.status(200).json({ success: true, message: 'Category deleted.' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to delete category.' });
  }
};

export const getTags = async (_req: Request, res: Response): Promise<void> => {
  try {
    const tags = await prisma.tag.findMany();
    res.status(200).json({ success: true, data: tags });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch tags.' });
  }
};

export const createTag = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { name, slug } = req.body;
    if (!name || !slug) {
      res.status(400).json({ success: false, message: 'Name and slug are required.' });
      return;
    }
    const tag = await prisma.tag.create({ data: { name, slug } });
    res.status(201).json({ success: true, data: tag });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to create tag.' });
  }
};

export const deleteTag = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    await prisma.tag.delete({ where: { id: req.params.id } });
    res.status(200).json({ success: true, message: 'Tag deleted.' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to delete tag.' });
  }
};

// ═══════════════════════════════════════════════════════════════════════════════
// SEO SETTINGS
// ═══════════════════════════════════════════════════════════════════════════════

export const getSeoByPath = async (req: Request, res: Response): Promise<void> => {
  try {
    let pathParam = req.params.path || '';
    let pagePath = decodeURIComponent(pathParam);
    if (!pagePath.startsWith('/')) {
      pagePath = '/' + pagePath;
    }
    const setting = await prisma.sEOSetting.findUnique({ where: { pagePath } });
    if (!setting) {
      res.status(404).json({ success: false, message: 'SEO setting not found.' });
      return;
    }
    res.status(200).json({ success: true, data: setting });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch SEO setting.' });
  }
};

export const upsertSeoSetting = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { pagePath, metaTitle, metaDescription, keywords, ogTitle, ogDescription, ogImage, schemaMarkup } = req.body;
    if (!pagePath || !metaTitle || !metaDescription) {
      res.status(400).json({ success: false, message: 'pagePath, metaTitle, and metaDescription are required.' });
      return;
    }
    const setting = await prisma.sEOSetting.upsert({
      where: { pagePath },
      update: { metaTitle, metaDescription, keywords: keywords || [], ogTitle, ogDescription, ogImage, schemaMarkup },
      create: { pagePath, metaTitle, metaDescription, keywords: keywords || [], ogTitle, ogDescription, ogImage, schemaMarkup },
    });
    res.status(200).json({ success: true, data: setting });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to save SEO setting.' });
  }
};

// ═══════════════════════════════════════════════════════════════════════════════
// DASHBOARD STATS
// ═══════════════════════════════════════════════════════════════════════════════

export const getDashboardStats = async (_req: AuthRequest, res: Response): Promise<void> => {
  try {
    const [services, products, projects, blogs, messages, testimonials] = await Promise.all([
      prisma.service.count(),
      prisma.product.count(),
      prisma.project.count(),
      prisma.blog.count(),
      prisma.contactMessage.count({ where: { status: 'UNREAD' } }),
      prisma.testimonial.count(),
    ]);
    res.status(200).json({
      success: true,
      data: { services, products, projects, blogs, unreadMessages: messages, testimonials },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch stats.' });
  }
};
